/// <reference types="react-native-css/types" />

// NOTE: This file is generated by react-native-css and it should not be edited manually.
// If you need to move or disable this file, please see the documentation.
